micronaut:
  application:
    name: demoliquibase
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /redoc/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /v3/api-docs/**
        access: isAnonymous()
      - pattern: /control-panel/**
        access: isAnonymous()
      - pattern: /routes/**
        access: isAnonymous()
      - pattern: /beans/**
        access: isAnonymous()
      - pattern: /openapi-explorer/**
        access: isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/demoDb
    username: postgres
    password: "changeme"
    driver-class-name: org.postgresql.Driver
    db-type: postgres
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
jpa.default.properties.hibernate.hbm2ddl.auto: none

endpoints:
  routes:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: true
